name: snuz_app
description: "snuz: sleep and meditation"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  app_links: ^6.3.2
  assets_audio_player: ^3.1.1
  cloud_functions:
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  firebase_app_check:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.3.0
  http: ^1.2.2
  hugeicons: ^0.0.10
  intl: ^0.20.2
  lottie: ^3.1.3
  path_provider: ^2.1.4
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.2
  wiredash: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/sleepcasts/
